<?php
/**
 * @file
 * Code for the DoSomething Action Finder feature.
 */

include_once 'dosomething_action_finder.features.inc';

/**
 * Implements hook_views_query_alter().
 */
function dosomething_action_finder_views_query_alter(&$view, &$query) {
  // Pop off the last few placeholder elements in the conditions array.
  // We needed the tables to be joined, but don't need the actual conditions.
  for ($i = 1; $i <= 6; $i++) {
    array_pop($query->where[1]['conditions']);
  }

  $query->fields['weight'] = array(
    'field' => '
      IF (field_high_season_value < CURDATE() AND field_high_season_value2 > CURDATE(), 5, -2)
      + IF ((field_high_season_value < CURDATE() AND field_high_season_value2 > CURDATE()) = 0 AND (field_low_season_value < CURDATE() AND field_low_season_value2 > CURDATE()) = 0, 3, 3)
      + IF (field_low_season_value < CURDATE() AND field_low_season_value2 > CURDATE(), -4, 2)
      + IF (field_staff_pick_value = 1, 2, 0)
      + IF (field_sponsored_value = 1, 1, 0)
    ',
    'table' => '',
    'alias' => 'season_weight',
  );
  $weight_order = array(
    'field' => 'season_weight',
    'direction' => 'DESC',
  );

  $query->orderby = array();
  array_unshift($query->orderby, $weight_order);
}
